apiVersion: v1
kind: Pod
metadata:
  name: busybox-env-secret
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy-env-secret
    command:
      - sleep
      - "3600"
    env:
    - name: MEU_USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-literal
          key: user
    - name: MEU_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-literal
          key: password
